# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-09-03 11:24:29
"""
import arcpy

def Model1():  # Reclassify LULC for RF Impedence

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")

    Esri_2020_Land_Cover_V2_lyrx = "C:\\OneDrive - Esri\\Documents\\ArcGIS\\Projects\\RF_Propagation\\Esri_2020_Land_Cover_V2.lyrx"

    # Process: Reclassify (Reclassify) (sa)
    LULC_Reclass_Impedance_Factor = "C:\\OneDrive - Esri\\Documents\\ArcGIS\\Projects\\RF_Propagation\\RF_Propagation.gdb\\LULC_Reclass_Impedance_Factor"
    Reclassify = LULC_Reclass_Impedance_Factor
    with arcpy.EnvManager(extent="452674.8201 3408980.9417 522997.9258 3488476.6264", mask="AOI", outputCoordinateSystem="PROJCS["WGS_1984_UTM_Zone_15N",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-93.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]"):
        LULC_Reclass_Impedance_Factor = arcpy.sa.Reclassify(in_raster=Esri_2020_Land_Cover_V2_lyrx, reclass_field="ClassName", remap="'No Data' NODATA;Water 3;Trees 8;Grass 3;'Flooded Vegetation' 6;Crops 5;Scrub/Shrub 7;'Built Area' 9;'Bare Ground' 1;Snow/Ice 4;Clouds 10", missing_values="DATA")
        LULC_Reclass_Impedance_Factor.save(Reclassify)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\OneDrive - Esri\Documents\ArcGIS\Projects\RF_Propagation\RF_Propagation.gdb", workspace=r"C:\OneDrive - Esri\Documents\ArcGIS\Projects\RF_Propagation\RF_Propagation.gdb"):
        Model1()
